on:
  push:
    branches:
      - master
      - capacitor-*
      - beta-*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16.6.1

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - run: npm install
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: package.json
          # if branch is master, publish as latest, overwise use the branch name
          tag: ${{ steps.extract_branch.outputs.branch == 'master' && 'latest' || steps.extract_branch.outputs.branch }}
